[project]
name = "lkpy"
version = "0.1.0"
description = "LK's Python Playground"
authors = [{ name = "Lasantha Kularatne" }]
requires-python = ">=3.8"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"